-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "storage"."files" add column "is_uploaded" boolean
--  not null default 'false';
